FROM quay.io/fedora/fedora-coreos:stable

RUN dnf install -y fsverity

COPY extra /

RUN set -x; \
    kver=$(cd /usr/lib/modules && echo *); \
    dracut -vf /usr/lib/modules/$kver/initramfs.img $kver;

RUN passwd -d root
