FROM quay.io/fedora/fedora-bootc:44

COPY extra /
COPY ./strace /strace

RUN set -x; \
    kver=$(cd /usr/lib/modules && echo *); \
    dracut -vf /usr/lib/modules/$kver/initramfs.img $kver;

RUN rm -rf /etc/yum.repos.d/fedora-cisco-openh264.repo
RUN dnf install -y nu vim xxd strace strings tree binutils systemd-ukify

# Install the new grub-cc binary

RUN <<EOF
arch=$(uname -m)
curl -L -o /var/grub-cc.rpm "https://kojipkgs.fedoraproject.org/packages/grub2/2.12/59.eln156/x86_64/grub2-efi-x64-cc-2.12-59.eln156.${arch}.rpm"
mkdir /var/grub-cc
rpm2archive /var/grub-cc.rpm | tar -xvz -C /var/grub-cc
file=$(find /var/grub-cc -name '*.efi')
mkdir /usr/lib/grub-cc
cp $file /usr/lib/grub-cc
rm -rvf /var/grub-cc
rm -rvf /var/grub-cc.rpm
EOF

COPY bootc /usr/bin

COPY ./bootc-finalize-staged.service /usr/lib/systemd/system

# For development
RUN sed -i "s;/usr/bin/bootc;/var/bootc;" /usr/lib/systemd/system/bootc-finalize-staged.service
COPY bootc /var/bootc

RUN mkdir -p /usr/lib/systemd/boot/efi
COPY systemd-bootx64.efi /usr/lib/systemd/boot/efi/systemd-bootx64.efi

RUN sed -i '/PasswordAuthentication/c\PasswordAuthentication yes' /etc/ssh/sshd_config
RUN sed -i '/PermitEmptyPasswords/c\PermitEmptyPasswords yes' /etc/ssh/sshd_config
RUN sed -i '/PermitRootLogin/c\PermitRootLogin yes' /etc/ssh/sshd_config

RUN cat >> /etc/containers/registries.conf <<-EOF
    [[registry]]
    location = "192.168.122.1:5000"
    insecure = true
EOF

RUN passwd -d root

RUN rm /home && mkdir /home

RUN <<RUNEOF

mkdir /etc/repart.d

cat <<EOF > /etc/repart.d/00-bios.conf
[Partition]
Type=21686148-6449-6e6f-744e-656564454649
Label=BIOS-BOOT
SizeMinBytes=1M
SizeMaxBytes=1M
EOF

cat <<EOF > /etc/repart.d/01-esp.conf
[Partition]
Type=esp
Format=vfat
SizeMinBytes=2048M
SizeMaxBytes=2048M
EOF

cat <<EOF > /etc/repart.d/02-home.conf
[Partition]
Type=home
Format=ext4
SizeMinBytes=2048M
SizeMaxBytes=2048M
EOF

# cat <<EOF > /etc/repart.d/01-sysroot.conf
# [Partition]
# Type=root
# Format=ext4
# SizeMaxBytes=13G
# EOF

RUNEOF
