FROM alpine


RUN mkdir /boot
RUN mkdir /sysroot
RUN mkdir -p "/usr/lib/modules/6.16.9-200.fc42.x86_64"
COPY ./kernel /usr/lib/modules/6.16.9-200.fc42.x86_64/vmlinuz
COPY ./initrd /usr/lib/modules/6.16.9-200.fc42.x86_64/initramfs.img
