FROM quay.io/fedora/fedora-coreos:stable

COPY cfsctl /usr/bin
COPY extra /

RUN set -x; \
    kver=$(cd /usr/lib/modules && echo *); \
    dracut -vf /usr/lib/modules/$kver/initramfs.img $kver;

RUN passwd -d root
