FROM localhost/bootc-centos9
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN yum install yum-utils -y dnf-plugins-core && yum-builddep -y ostree
RUN dnf -y install libzstd-devel openssl-devel ostree-devel
ENV PATH="/root/.cargo/bin:${PATH}"
RUN passwd -d root
