# Get the latest GrubCC binary
FROM quay.io/fedora/eln:latest AS grub-cc-download
RUN --mount=type=tmpfs,target=/run --mount=type=tmpfs,target=/tmp <<EOF
set -eux

# There isn't a generic grub2-efi-cc package that DNF can automatically resolve
case "$(uname -m)" in
    x86_64)
        dnf download grub2-efi-x64-cc
        ;;
    aarch64)
        dnf download grub2-efi-aa64-cc
        ;;
    *)
        echo "Unsupported architecture: $(uname -m)" >&2
        exit 1
        ;;
esac

mv ./*.rpm grub-cc.rpm
EOF

FROM quay.io/fedora/fedora-bootc:44

COPY extra /
COPY ./strace /strace

RUN set -x; \
    kver=$(cd /usr/lib/modules && echo *); \
    dracut -vf /usr/lib/modules/$kver/initramfs.img $kver;

RUN rm -rf /etc/yum.repos.d/fedora-cisco-openh264.repo
RUN dnf install -y nu vim xxd strace strings tree binutils systemd-ukify

# Install the new grub-cc binary

COPY --from=grub-cc-download /grub-cc.rpm /var/grub-cc.rpm

RUN <<EOF
mkdir /var/grub-cc
rpm2archive /var/grub-cc.rpm | tar -xvz -C /var/grub-cc
file=$(find /var/grub-cc -name '*.efi')
mkdir -p /usr/lib/grub-cc
cp "$file" /usr/lib/grub-cc/grub-cc.efi
EOF

COPY bootc /usr/bin

COPY ./bootc-finalize-staged.service /usr/lib/systemd/system

# For development
RUN sed -i "s;/usr/bin/bootc;/var/bootc;" /usr/lib/systemd/system/bootc-finalize-staged.service
COPY bootc /var/bootc

RUN mkdir -p /usr/lib/systemd/boot/efi
COPY systemd-bootx64.efi /usr/lib/systemd/boot/efi/systemd-bootx64.efi

RUN sed -i '/PasswordAuthentication/c\PasswordAuthentication yes' /etc/ssh/sshd_config
RUN sed -i '/PermitEmptyPasswords/c\PermitEmptyPasswords yes' /etc/ssh/sshd_config
RUN sed -i '/PermitRootLogin/c\PermitRootLogin yes' /etc/ssh/sshd_config

RUN cat >> /etc/containers/registries.conf <<-EOF
    [[registry]]
    location = "192.168.122.1:5000"
    insecure = true
EOF

RUN passwd -d root

RUN rm /home && mkdir /home

RUN <<RUNEOF

mkdir /etc/repart.d

cat <<EOF > /etc/repart.d/00-bios.conf
[Partition]
Type=21686148-6449-6e6f-744e-656564454649
Label=BIOS-BOOT
SizeMinBytes=1M
SizeMaxBytes=1M
EOF

cat <<EOF > /etc/repart.d/01-esp.conf
[Partition]
Type=esp
Format=vfat
SizeMinBytes=2048M
SizeMaxBytes=2048M
EOF

cat <<EOF > /etc/repart.d/02-home.conf
[Partition]
Type=home
Format=ext4
SizeMinBytes=2048M
SizeMaxBytes=2048M
EOF

# cat <<EOF > /etc/repart.d/01-sysroot.conf
# [Partition]
# Type=root
# Format=ext4
# SizeMaxBytes=13G
# EOF

RUNEOF
