FROM quay.io/fedora/fedora-bootc:44

RUN <<EOF
    # We have this until we get grub-cc support in bootupd
    arch=$(uname -m)
    curl -L -o /var/grub-cc.rpm "https://kojipkgs.fedoraproject.org/packages/grub2/2.12/59.fc45/x86_64/grub2-efi-x64-cc-2.12-59.fc45.${arch}.rpm"
    mkdir /var/grub-cc
    rpm2archive /var/grub-cc.rpm | tar -xvz -C /var/grub-cc

    mkdir -p /usr/lib/efi/grub-cc/1:2.12-59.fc45/EFI/fedora

    the_file=$(find /var/grub-cc -name 'grubx64-cc.efi')

    mv "$the_file" /usr/lib/efi/grub-cc/1:2.12-59.fc45/EFI/fedora/grubx64-cc.efi
EOF

RUN rm -rf /var/lib/cache/dnf5
RUN dnf install -y systemd-boot-unsigned

# Install systemd-boot
RUN --mount=type=tmpfs,target=/run --mount=type=tmpfs,target=/tmp <<EOF
set -eux
# epoch for systemd-boot-unsigned is "(none)"
evr=$(rpm -q --qf '%{VERSION}-%{RELEASE}\n' systemd-boot-unsigned)
rpm -ql systemd-boot-unsigned

. /etc/os-release

# Create the expected directory structure at /usr/lib/efi/systemd-boot/<evr>/EFI/fedora/
mkdir -p "/usr/lib/efi/systemd-boot/${evr}/EFI/$ID"

if [[ $(uname -m) == x86_64 ]]; then
    grubName="grubx64.efi"
else
    grubName="grubaa64.efi"
fi

cp /usr/lib/systemd/boot/efi/systemd-boot*.efi "/usr/lib/efi/systemd-boot/${evr}/EFI/$ID/$grubName"

EOF

COPY ./bootupd /usr/sbin/bootupctl

RUN bootupctl backend generate-update-metadata
RUN bootupctl backend set-default-bootloader grub
